config/routes.rb
Lmi::Application.routes.draw do
  
  match "/linkedins/index" => "linkedins#index"
  match "/linkedins/callback" => "linkedins#callback"

  resources :in_demand
  root :to => 'in_demand#index'
end

app/models/linkedin.rb
class Linkedin < ActiveRecord::Base
  # attr_accessible :title, :body
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/in_demand_controller.rb
class InDemandController < ApplicationController
end

app/controllers/linkedins_controller.rb
#uncomment the line below if you aren't using bundler
#require 'rubygems'
#require 'linkedin'

class LinkedinsController < ApplicationController

  def index
    # get your api keys at https://www.linkedin.com/secure/developer
    client = LinkedIn::Client.new("lI6W0aPijmrR4FaqePmRTNjw8dJIoMqtA94Z_3NzEEe4odUCtEN4Btwd_Nfzzs4A", "BsC51hSk-SaoNSxSG5Aa2kSfa4G6wc-3jLUqiU-BWkJ5dc32iFtzl12SU_grDJIn")
    request_token = client.request_token(:oauth_callback =>"http://#{request.host_with_port}/auth/callback")
    session[:rtoken] = request_token.token
    session[:rsecret] = request_token.secret

    redirect_to client.request_token.authorize_url

  end

  def callback
    client = LinkedIn::Client.new("your_api_key", "your_secret")
    if session[:atoken].nil?
      pin = params[:oauth_verifier]
      atoken, asecret = client.authorize_from_request(session[:rtoken], session[:rsecret], pin)
      session[:atoken] = atoken
      session[:asecret] = asecret
    else
      client.authorize_from_access(session[:atoken], session[:asecret])
    end
    @profile = client.profile
    @connections = client.connections
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/in_demand_helper.rb
module InDemandHelper
end

app/helpers/linkedins_helper.rb
module LinkedinsHelper
end

app/views/in_demand/index.html.erb
<div class='span9'>
    <div id='instructions'>
        <p>Choose a region and start exploring.</p>
        
        <p>Every time you search you'll see a different selection of the most in demand jobs in your area.</p>
        
    </div>
    <div id='job_detail'>
    
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lmi" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


</head>
<body>  

    <!-- 
    <div class="navbar navbar-fluid-top">
    <div class="navbar-inner">
    <div class="container-fluid">
    <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
    <a class="brand" href="#">Which jobs are most in demand?</a>
    <div class="container-fluid nav-collapse">

</div>
</div>
</div>
</div>

-->

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3 offset1">
            <div class="well sidebar-nav">
                <select id='region_selector'>
                    <option value='choose'> Where are you? </option>
                    <option value='1'>London</option>
                    <option value='3'>East of England</option>
                    <option value='2'>South East (England)</option>
                    <option value='4'>South West (England)</option>
                    <option value='10'>Wales</option>
                    <option value='7'>Yorkshire and the Humber</option>
                    <option value='11'>Scotland</option>
                    <option value='6'>East Midlands (England)</option>
                    <option value='9'>North East (England)</option>
                    <option value='8'>North West (England)</option>
                    <option value='12'>Northern Ireland</option>
                    <option value='5'>West Midlands (England)</option>
                </select>

                <div class='btn btn-default trigger_search'>
                    See some career options
                </div>
            </div>

            <div class="well sidebar-nav job_choices">
                <ol id='results_container'>
                    
                </ol>
            </div>

        </div><!--/span-->
        <div class="span8">
            <%= bootstrap_flash %>
            <%= yield %>
        </div>
    </div><!--/row-->

    <footer>

    </footer>

</div> <!-- /container -->

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/linkedins/_form.html.erb
<%= form_for(@linkedin) do |f| %>
  <% if @linkedin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linkedin.errors.count, "error") %> prohibited this linkedin from being saved:</h2>

      <ul>
      <% @linkedin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/linkedins/edit.html.erb
<h1>Editing linkedin</h1>

<%= render 'form' %>

<%= link_to 'Show', @linkedin %> |
<%= link_to 'Back', linkedins_path %>

app/views/linkedins/index.html.erb
<h1>Listing linkedins</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @linkedins.each do |linkedin| %>
  <tr>
    <td><%= link_to 'Show', linkedin %></td>
    <td><%= link_to 'Edit', edit_linkedin_path(linkedin) %></td>
    <td><%= link_to 'Destroy', linkedin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Linkedin', new_linkedin_path %>

app/views/linkedins/new.html.erb
<h1>New linkedin</h1>

<%= render 'form' %>

<%= link_to 'Back', linkedins_path %>

app/views/linkedins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_linkedin_path(@linkedin) %> |
<%= link_to 'Back', linkedins_path %>